import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('raceEngineer', {
  startTelemetry: (port) => ipcRenderer.send('start-telemetry', port),
  stopTelemetry: () => ipcRenderer.send('stop-telemetry'),
  setManualTrack: (trackId) => ipcRenderer.send('set-manual-track', trackId),
  setApiKey: (key) => ipcRenderer.send('set-api-key', key),
  saveSettings: (settings) => ipcRenderer.send('save-settings', settings),
  loadSettings: () => ipcRenderer.invoke('load-settings'),
  ttsSpeak: (payload) => ipcRenderer.invoke('tts-speak', payload),
  askEngineer: (payload) => ipcRenderer.invoke('ask-engineer', payload),
  getLookups: () => ipcRenderer.invoke('get-lookups'),
  openWindow: (opts) => ipcRenderer.invoke('open-window', opts),
  setWindowTitle: (title) => ipcRenderer.send('set-window-title', title),
  getStateSnapshot: () => ipcRenderer.invoke('get-state-snapshot'),
  saveExportFile: (payload) => ipcRenderer.invoke('save-export-file', payload),
  loadRaceAnalysisDraft: () => ipcRenderer.invoke('load-race-analysis-draft'),
  saveRaceAnalysisDraft: (payload) => ipcRenderer.invoke('save-race-analysis-draft', payload),
  listRaceAnalysisSnapshots: () => ipcRenderer.invoke('list-race-analysis-snapshots'),
  saveRaceAnalysisSnapshot: (payload) => ipcRenderer.invoke('save-race-analysis-snapshot', payload),

  gptRealtimeConnect: (payload) => ipcRenderer.invoke('gpt-realtime-connect', payload),
  gptRealtimeDisconnect: () => ipcRenderer.invoke('gpt-realtime-disconnect'),
  gptRealtimePush: (payload) => ipcRenderer.invoke('gpt-realtime-push', payload),
  gptRealtimeStatus: () => ipcRenderer.invoke('gpt-realtime-status'),

  getLicense: () => ipcRenderer.invoke('get-license'),
  getPricingPacks: (opts) => ipcRenderer.invoke('get-pricing-packs', opts),
  getPaymentOptions: () => ipcRenderer.invoke('get-payment-options'),
  setBYOKMode: (payload) => ipcRenderer.invoke('set-byok-mode', payload),
  stripeCheckout: (payload) => ipcRenderer.invoke('stripe-checkout', payload),
  stripeVerifySession: (payload) => ipcRenderer.invoke('stripe-verify-session', payload),
  startDevSession: () => ipcRenderer.invoke('start-dev-session'),
  activateLicenseKey: (payload) => ipcRenderer.invoke('activate-license-key', payload),
  deactivateLicenseKey: () => ipcRenderer.invoke('deactivate-license-key'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onStripeReturn: (cb) => ipcRenderer.on('stripe-return', (_, d) => cb(d)),

  onTelemetryStarted: (cb) => ipcRenderer.on('telemetry-started', (_, d) => cb(d)),
  onTelemetryStopped: (cb) => ipcRenderer.on('telemetry-stopped', (_, d) => cb(d)),
  onTelemetryError: (cb) => ipcRenderer.on('telemetry-error', (_, d) => cb(d)),
  onSessionUpdate: (cb) => ipcRenderer.on('session-update', (_, d) => cb(d)),
  onLapUpdate: (cb) => ipcRenderer.on('lap-update', (_, d) => cb(d)),
  onTelemetryUpdate: (cb) => ipcRenderer.on('telemetry-update', (_, d) => cb(d)),
  onSetupUpdate: (cb) => ipcRenderer.on('setup-update', (_, d) => cb(d)),
  onStatusUpdate: (cb) => ipcRenderer.on('status-update', (_, d) => cb(d)),
  onDamageUpdate: (cb) => ipcRenderer.on('damage-update', (_, d) => cb(d)),
  onParticipantsUpdate: (cb) => ipcRenderer.on('participants-update', (_, d) => cb(d)),
  onAllSetupUpdate: (cb) => ipcRenderer.on('allsetup-update', (_, d) => cb(d)),
  onAllStatusUpdate: (cb) => ipcRenderer.on('allstatus-update', (_, d) => cb(d)),
  onAllTelemetryUpdate: (cb) => ipcRenderer.on('alltelemetry-update', (_, d) => cb(d)),
  onBestLapsUpdate: (cb) => ipcRenderer.on('best-laps-update', (_, d) => cb(d)),
  onFastestLapUpdate: (cb) => ipcRenderer.on('fastest-lap-update', (_, d) => cb(d)),
  onEventUpdate: (cb) => ipcRenderer.on('event-update', (_, d) => cb(d)),

  onGptAudioChunk: (cb) => ipcRenderer.on('gpt-audio-chunk', (_, d) => cb(d)),
  onGptTranscript: (cb) => ipcRenderer.on('gpt-transcript', (_, d) => cb(d)),
  onGptStatus: (cb) => ipcRenderer.on('gpt-status', (_, d) => cb(d)),
  onLicenseUpdate: (cb) => ipcRenderer.on('license-update', (_, d) => cb(d)),
});

